---
- hosts: host1
  gather_facts: false
  become: true
  name: Play 1
  tasks:
     - setup:
        filter: ansible_*
     - name: Execute command ‘Date’
       command: date
     - name: Execute script on server
       script: test_script.sh
     - name: Install nginx
       apt: name=nginx state=latest