# ansible yaml playbook to both install nginx and install a sample code from git repo

---
- hosts: host1
  gather_facts: false
  become: yes
  tasks:
    - setup:
        filter: ansible_*
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Start NGINX service
      service:
        name: nginx
        state: started